import { SelectOption } from "@/models/form";

/**
 * 대한민국 행정구역 데이터
 * 시/도 → 구/군 → 동/읍/면 계층 구조
 */

// 시/도 목록 (17개 광역자치단체)
export const cityOptions: SelectOption[] = [
  { value: "seoul", label: "서울특별시" },
  { value: "busan", label: "부산광역시" },
  { value: "daegu", label: "대구광역시" },
  { value: "incheon", label: "인천광역시" },
  { value: "gwangju", label: "광주광역시" },
  { value: "daejeon", label: "대전광역시" },
  { value: "ulsan", label: "울산광역시" },
  { value: "sejong", label: "세종특별자치시" },
  { value: "gyeonggi", label: "경기도" },
  { value: "gangwon", label: "강원특별자치도" },
  { value: "chungbuk", label: "충청북도" },
  { value: "chungnam", label: "충청남도" },
  { value: "jeonbuk", label: "전북특별자치도" },
  { value: "jeonnam", label: "전라남도" },
  { value: "gyeongbuk", label: "경상북도" },
  { value: "gyeongnam", label: "경상남도" },
  { value: "jeju", label: "제주특별자치도" },
];

// 시/도별 구/군 목록
export const districtsByCity: Record<string, SelectOption[]> = {
  seoul: [
    { value: "gangnam", label: "강남구" },
    { value: "gangdong", label: "강동구" },
    { value: "gangbuk", label: "강북구" },
    { value: "gangseo", label: "강서구" },
    { value: "gwanak", label: "관악구" },
    { value: "gwangjin", label: "광진구" },
    { value: "guro", label: "구로구" },
    { value: "geumcheon", label: "금천구" },
    { value: "nowon", label: "노원구" },
    { value: "dobong", label: "도봉구" },
    { value: "dongdaemun", label: "동대문구" },
    { value: "dongjak", label: "동작구" },
    { value: "mapo", label: "마포구" },
    { value: "seodaemun", label: "서대문구" },
    { value: "seocho", label: "서초구" },
    { value: "seongdong", label: "성동구" },
    { value: "seongbuk", label: "성북구" },
    { value: "songpa", label: "송파구" },
    { value: "yangcheon", label: "양천구" },
    { value: "yeongdeungpo", label: "영등포구" },
    { value: "yongsan", label: "용산구" },
    { value: "eunpyeong", label: "은평구" },
    { value: "jongno", label: "종로구" },
    { value: "jung", label: "중구" },
    { value: "jungnang", label: "중랑구" },
  ],
  busan: [
    { value: "gangseo_bs", label: "강서구" },
    { value: "geumjeong", label: "금정구" },
    { value: "gijang", label: "기장군" },
    { value: "nam_bs", label: "남구" },
    { value: "dong_bs", label: "동구" },
    { value: "dongnae", label: "동래구" },
    { value: "busanjin", label: "부산진구" },
    { value: "buk_bs", label: "북구" },
    { value: "sasang", label: "사상구" },
    { value: "saha", label: "사하구" },
    { value: "seo_bs", label: "서구" },
    { value: "suyeong", label: "수영구" },
    { value: "yeonje", label: "연제구" },
    { value: "yeongdo", label: "영도구" },
    { value: "jung_bs", label: "중구" },
    { value: "haeundae", label: "해운대구" },
  ],
  daegu: [
    { value: "nam_dg", label: "남구" },
    { value: "dalseo", label: "달서구" },
    { value: "dalseong", label: "달성군" },
    { value: "dong_dg", label: "동구" },
    { value: "buk_dg", label: "북구" },
    { value: "seo_dg", label: "서구" },
    { value: "suseong", label: "수성구" },
    { value: "jung_dg", label: "중구" },
  ],
  incheon: [
    { value: "ganghwa", label: "강화군" },
    { value: "gyeyang", label: "계양구" },
    { value: "namdong", label: "남동구" },
    { value: "dong_ic", label: "동구" },
    { value: "michuhol", label: "미추홀구" },
    { value: "bupyeong", label: "부평구" },
    { value: "seo_ic", label: "서구" },
    { value: "yeonsu", label: "연수구" },
    { value: "ongjin", label: "옹진군" },
    { value: "jung_ic", label: "중구" },
  ],
  gwangju: [
    { value: "gwangsan", label: "광산구" },
    { value: "nam_gj", label: "남구" },
    { value: "dong_gj", label: "동구" },
    { value: "buk_gj", label: "북구" },
    { value: "seo_gj", label: "서구" },
  ],
  daejeon: [
    { value: "daedeok", label: "대덕구" },
    { value: "dong_dj", label: "동구" },
    { value: "seo_dj", label: "서구" },
    { value: "yuseong", label: "유성구" },
    { value: "jung_dj", label: "중구" },
  ],
  ulsan: [
    { value: "nam_us", label: "남구" },
    { value: "dong_us", label: "동구" },
    { value: "buk_us", label: "북구" },
    { value: "ulju", label: "울주군" },
    { value: "jung_us", label: "중구" },
  ],
  sejong: [
    { value: "sejong_city", label: "세종시" },
  ],
  gyeonggi: [
    { value: "gapyeong", label: "가평군" },
    { value: "goyang", label: "고양시" },
    { value: "gwacheon", label: "과천시" },
    { value: "gwangmyeong", label: "광명시" },
    { value: "gwangju_gg", label: "광주시" },
    { value: "guri", label: "구리시" },
    { value: "gunpo", label: "군포시" },
    { value: "gimpo", label: "김포시" },
    { value: "namyangju", label: "남양주시" },
    { value: "dongducheon", label: "동두천시" },
    { value: "bucheon", label: "부천시" },
    { value: "seongnam", label: "성남시" },
    { value: "suwon", label: "수원시" },
    { value: "siheung", label: "시흥시" },
    { value: "ansan", label: "안산시" },
    { value: "anseong", label: "안성시" },
    { value: "anyang", label: "안양시" },
    { value: "yangju", label: "양주시" },
    { value: "yangpyeong", label: "양평군" },
    { value: "yeoju", label: "여주시" },
    { value: "yeoncheon", label: "연천군" },
    { value: "osan", label: "오산시" },
    { value: "yongin", label: "용인시" },
    { value: "uiwang", label: "의왕시" },
    { value: "uijeongbu", label: "의정부시" },
    { value: "icheon", label: "이천시" },
    { value: "paju", label: "파주시" },
    { value: "pyeongtaek", label: "평택시" },
    { value: "pocheon", label: "포천시" },
    { value: "hanam", label: "하남시" },
    { value: "hwaseong", label: "화성시" },
  ],
  gangwon: [
    { value: "gangneung", label: "강릉시" },
    { value: "goseong_gw", label: "고성군" },
    { value: "donghae", label: "동해시" },
    { value: "samcheok", label: "삼척시" },
    { value: "sokcho", label: "속초시" },
    { value: "yanggu", label: "양구군" },
    { value: "yangyang", label: "양양군" },
    { value: "yeongwol", label: "영월군" },
    { value: "wonju", label: "원주시" },
    { value: "inje", label: "인제군" },
    { value: "jeongseon", label: "정선군" },
    { value: "cheorwon", label: "철원군" },
    { value: "chuncheon", label: "춘천시" },
    { value: "taebaek", label: "태백시" },
    { value: "pyeongchang", label: "평창군" },
    { value: "hongcheon", label: "홍천군" },
    { value: "hwacheon", label: "화천군" },
    { value: "hoengseong", label: "횡성군" },
  ],
  chungbuk: [
    { value: "goesan", label: "괴산군" },
    { value: "danyang", label: "단양군" },
    { value: "boeun", label: "보은군" },
    { value: "yeongdong", label: "영동군" },
    { value: "okcheon", label: "옥천군" },
    { value: "eumseong", label: "음성군" },
    { value: "jecheon", label: "제천시" },
    { value: "jeungpyeong", label: "증평군" },
    { value: "jincheon", label: "진천군" },
    { value: "cheongju", label: "청주시" },
    { value: "chungju", label: "충주시" },
  ],
  chungnam: [
    { value: "gyeryong", label: "계룡시" },
    { value: "gongju", label: "공주시" },
    { value: "geumsan", label: "금산군" },
    { value: "nonsan", label: "논산시" },
    { value: "dangjin", label: "당진시" },
    { value: "boryeong", label: "보령시" },
    { value: "buyeo", label: "부여군" },
    { value: "seosan", label: "서산시" },
    { value: "seocheon", label: "서천군" },
    { value: "asan", label: "아산시" },
    { value: "yesan", label: "예산군" },
    { value: "cheonan", label: "천안시" },
    { value: "cheongyang", label: "청양군" },
    { value: "taean", label: "태안군" },
    { value: "hongseong", label: "홍성군" },
  ],
  jeonbuk: [
    { value: "gochang", label: "고창군" },
    { value: "gunsan", label: "군산시" },
    { value: "gimje", label: "김제시" },
    { value: "namwon", label: "남원시" },
    { value: "muju", label: "무주군" },
    { value: "buan", label: "부안군" },
    { value: "sunchang", label: "순창군" },
    { value: "wanju", label: "완주군" },
    { value: "iksan", label: "익산시" },
    { value: "imsil", label: "임실군" },
    { value: "jangsu", label: "장수군" },
    { value: "jeonju", label: "전주시" },
    { value: "jeongeup", label: "정읍시" },
    { value: "jinan", label: "진안군" },
  ],
  jeonnam: [
    { value: "gangjin", label: "강진군" },
    { value: "goheung", label: "고흥군" },
    { value: "gokseong", label: "곡성군" },
    { value: "gwangyang", label: "광양시" },
    { value: "gurye", label: "구례군" },
    { value: "naju", label: "나주시" },
    { value: "damyang", label: "담양군" },
    { value: "mokpo", label: "목포시" },
    { value: "muan", label: "무안군" },
    { value: "boseong", label: "보성군" },
    { value: "suncheon", label: "순천시" },
    { value: "sinan", label: "신안군" },
    { value: "yeosu", label: "여수시" },
    { value: "yeonggwang", label: "영광군" },
    { value: "yeongam", label: "영암군" },
    { value: "wando", label: "완도군" },
    { value: "jangseong", label: "장성군" },
    { value: "jangheung", label: "장흥군" },
    { value: "jindo", label: "진도군" },
    { value: "hampyeong", label: "함평군" },
    { value: "haenam", label: "해남군" },
    { value: "hwasun", label: "화순군" },
  ],
  gyeongbuk: [
    { value: "gyeongsan", label: "경산시" },
    { value: "gyeongju", label: "경주시" },
    { value: "goryeong", label: "고령군" },
    { value: "gumi", label: "구미시" },
    { value: "gunwi", label: "군위군" },
    { value: "gimcheon", label: "김천시" },
    { value: "mungyeong", label: "문경시" },
    { value: "bonghwa", label: "봉화군" },
    { value: "sangju", label: "상주시" },
    { value: "seongju", label: "성주군" },
    { value: "andong", label: "안동시" },
    { value: "yeongdeok", label: "영덕군" },
    { value: "yeongyang", label: "영양군" },
    { value: "yeongju", label: "영주시" },
    { value: "yeongcheon", label: "영천시" },
    { value: "yecheon", label: "예천군" },
    { value: "ulleung", label: "울릉군" },
    { value: "uiseong", label: "의성군" },
    { value: "cheongdo", label: "청도군" },
    { value: "cheongsong", label: "청송군" },
    { value: "chilgok", label: "칠곡군" },
    { value: "pohang", label: "포항시" },
  ],
  gyeongnam: [
    { value: "geoje", label: "거제시" },
    { value: "geochang", label: "거창군" },
    { value: "goseong_gn", label: "고성군" },
    { value: "gimhae", label: "김해시" },
    { value: "namhae", label: "남해군" },
    { value: "miryang", label: "밀양시" },
    { value: "sacheon", label: "사천시" },
    { value: "sancheong", label: "산청군" },
    { value: "yangsan", label: "양산시" },
    { value: "uiryeong", label: "의령군" },
    { value: "jinju", label: "진주시" },
    { value: "changnyeong", label: "창녕군" },
    { value: "changwon", label: "창원시" },
    { value: "tongyeong", label: "통영시" },
    { value: "hadong", label: "하동군" },
    { value: "haman", label: "함안군" },
    { value: "hamyang", label: "함양군" },
    { value: "hapcheon", label: "합천군" },
  ],
  jeju: [
    { value: "jeju_city", label: "제주시" },
    { value: "seogwipo", label: "서귀포시" },
  ],
};

// 구/군별 동/읍/면 목록 (주요 지역만 포함 - 데이터 양이 많아 주요 지역 위주)
export const dongsByDistrict: Record<string, SelectOption[]> = {
  // 서울 서초구
  seocho: [
    { value: "seocho1", label: "서초1동" },
    { value: "seocho2", label: "서초2동" },
    { value: "seocho3", label: "서초3동" },
    { value: "seocho4", label: "서초4동" },
    { value: "jamwon", label: "잠원동" },
    { value: "banpo1", label: "반포1동" },
    { value: "banpo2", label: "반포2동" },
    { value: "banpo3", label: "반포3동" },
    { value: "banpo4", label: "반포4동" },
    { value: "bangbae1", label: "방배1동" },
    { value: "bangbae2", label: "방배2동" },
    { value: "bangbae3", label: "방배3동" },
    { value: "bangbae4", label: "방배4동" },
    { value: "bangbaebon", label: "방배본동" },
    { value: "yangjae1", label: "양재1동" },
    { value: "yangjae2", label: "양재2동" },
    { value: "naegok", label: "내곡동" },
  ],
  // 서울 강남구
  gangnam: [
    { value: "sinsa", label: "신사동" },
    { value: "nonhyeon1", label: "논현1동" },
    { value: "nonhyeon2", label: "논현2동" },
    { value: "apgujeong", label: "압구정동" },
    { value: "cheongdam", label: "청담동" },
    { value: "samsung1", label: "삼성1동" },
    { value: "samsung2", label: "삼성2동" },
    { value: "daechi1", label: "대치1동" },
    { value: "daechi2", label: "대치2동" },
    { value: "daechi4", label: "대치4동" },
    { value: "yeoksam1", label: "역삼1동" },
    { value: "yeoksam2", label: "역삼2동" },
    { value: "dogok1", label: "도곡1동" },
    { value: "dogok2", label: "도곡2동" },
    { value: "gaepo1", label: "개포1동" },
    { value: "gaepo2", label: "개포2동" },
    { value: "gaepo4", label: "개포4동" },
    { value: "ilwonbon", label: "일원본동" },
    { value: "ilwon1", label: "일원1동" },
    { value: "ilwon2", label: "일원2동" },
    { value: "suseo", label: "수서동" },
    { value: "segok", label: "세곡동" },
  ],
  // 서울 송파구
  songpa: [
    { value: "pungnap1", label: "풍납1동" },
    { value: "pungnap2", label: "풍납2동" },
    { value: "geoyeo1", label: "거여1동" },
    { value: "geoyeo2", label: "거여2동" },
    { value: "macheon1", label: "마천1동" },
    { value: "macheon2", label: "마천2동" },
    { value: "bangi1", label: "방이1동" },
    { value: "bangi2", label: "방이2동" },
    { value: "oryun", label: "오륜동" },
    { value: "ogeum", label: "오금동" },
    { value: "songpa1", label: "송파1동" },
    { value: "songpa2", label: "송파2동" },
    { value: "seokchon", label: "석촌동" },
    { value: "samjeon", label: "삼전동" },
    { value: "garak1", label: "가락1동" },
    { value: "garak2", label: "가락2동" },
    { value: "munjeong1", label: "문정1동" },
    { value: "munjeong2", label: "문정2동" },
    { value: "jamsil1", label: "잠실본동" },
    { value: "jamsil2", label: "잠실2동" },
    { value: "jamsil3", label: "잠실3동" },
    { value: "jamsil4", label: "잠실4동" },
    { value: "jamsil6", label: "잠실6동" },
    { value: "jamsil7", label: "잠실7동" },
    { value: "wirye1", label: "위례동" },
  ],
  // 서울 강동구
  gangdong: [
    { value: "gangil", label: "강일동" },
    { value: "sangil1", label: "상일1동" },
    { value: "sangil2", label: "상일2동" },
    { value: "myeongil1", label: "명일1동" },
    { value: "myeongil2", label: "명일2동" },
    { value: "godeok1", label: "고덕1동" },
    { value: "godeok2", label: "고덕2동" },
    { value: "amsa1", label: "암사1동" },
    { value: "amsa2", label: "암사2동" },
    { value: "amsa3", label: "암사3동" },
    { value: "cheonho1", label: "천호1동" },
    { value: "cheonho2", label: "천호2동" },
    { value: "cheonho3", label: "천호3동" },
    { value: "seongnae1", label: "성내1동" },
    { value: "seongnae2", label: "성내2동" },
    { value: "seongnae3", label: "성내3동" },
    { value: "dunchon1", label: "둔촌1동" },
    { value: "dunchon2", label: "둔촌2동" },
  ],
};

/**
 * 시/도 선택에 따른 구/군 목록 반환
 */
export function getDistrictsByCity(cityValue: string): SelectOption[] {
  return districtsByCity[cityValue] || [];
}

/**
 * 구/군 선택에 따른 동/읍/면 목록 반환
 * 데이터가 없는 경우 빈 배열 반환
 */
export function getDongsByDistrict(districtValue: string): SelectOption[] {
  return dongsByDistrict[districtValue] || [];
}
